
spring:
  profiles: default
  rabbitmq:
    port: 5672

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=finalTaskdb
    username: "sa"
    password: "Sup3r-S3cr3t"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server


    hibernate:
      ddl-auto: update

liquibase:
  change-log: classpath:db/liquibase-changelog.xml

---

spring:
  profiles: test
  rabbitmq:
    port: 5672

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=TestDB
    username: "sa"
    password: "Sup3r-S3cr3t"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server


    hibernate:
      ddl-auto: create-drop


liquibase:
  change-log: classpath:db/liquibase-changelog.xml